-

- hosts: all
  become: true
  tasks:

   - name: Update repository index (for Red Hat-based systems)
      yum:
        name: '*'
        state: latest
         when: ansible_os_family == 'RedHat'

   - name: Install Apache (httpd or apache2)
     package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present
